create table public.anomalies (
  id bigint generated by default as identity not null,
  content text null,
  "ticId" text null,
  anomalytype text null,
  created_at timestamp with time zone not null default now(),
  configuration jsonb null,
  "parentAnomaly" bigint null,
  "anomalySet" text null,
  "anomalyConfiguration" jsonb null,
  constraint baseplanets_pkey primary key (id),
  constraint anomalies_parentAnomaly_fkey foreign key ("parentAnomaly") references anomalies (id)
) tablespace pg_default;
